### PR TITLE
Replaced lodash dep with es5 filtering

### PR DESCRIPTION
**Pull request by robinvdvleuten**
Hi!

I've replaced the lodash "uniq" dependency from the project with a es5 filtering method, so it depends on "react-side-effect" only :)

Cheers!
Robin

### CODE REVIEW

**Comment by iest** [comment]
I like it! This project's been a bit dormant since I left PactCoffee, looking to transfer ownership now so it can be maintained.

**Comment by robinvdvleuten** [comment]
I can take the maintenance on me. We use this lib in one of our production apps, so it would be a good fit there 😀

**Comment by iest** [comment]
Oh no I meant — transfer ownership to my own account so I can keep it maintained (rather than have it under my old employer's org). But thanks for the offer!

**Comment by robinvdvleuten** [comment]
Ah I've read it wrongly then, excusez moi

**Review by iest — APPROVED** [review]
Works a treat! Thanks for the PR. Releasing shortly.

**Comment by iest** [comment]
Made it into https://github.com/iest/react-body-classname/releases/tag/v1.1.0

**Pull request merged**
